### ISSUE TITLE
Bug: Android widget not updating

### ISSUE THREAD

**Issue by kreuselh** [khpylon/MachEWidget#10] opened 2022-03-11 13:10 UTC

**Comment by zhackwyatt** [comment] 2022-03-18 16:05
> mache_logfile.txt

You may want to sanitize that log file as it has some personally identifiable information.

**Comment by khpylon** [comment] 2022-03-18 16:17
> > mache_logfile.txt
> 
> You may want to sanitize that log file as it has some personally identifiable information.

Thanks. I redacted it.

**Comment by khpylon** [comment] 2022-03-29 01:56
So let me know if the problem is fixed with the latest update.

**Closed as completed** 2022-04-09 21:41 UTC
Labels: bug
