### ISSUE TITLE
Not updating

### ISSUE THREAD

**Issue by skiingj** [khpylon/MachEWidget#7] opened 2022-02-10 02:26 UTC
Widget not updating the last few days.  Updated to 2.09 today still not updating.  Thanks for all the hard work!  Greet widget!

**Comment by khpylon** [comment] 2022-02-11 18:06
Duplicate of [this issue](https://github.com/khpylon/MachEWidget/issues/6).

**Closed as completed by khpylon** 2022-02-11 18:06 UTC
Labels: duplicate
